alias xs='cd'
alias vf='cd'
alias moer='more'
alias moew='more'
alias kk='ll'
alias cls='clear'
alias celar='clear'
alias ckear='clear'
alias rm='rm -iv'
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -p'
alias more='less'
alias nc='nc -v'
alias which='type -a'
alias ..='cd ..'
alias du='du -kh'       # more readable output
alias df='df -Tha --total'
alias ls='ls -h --time-style=+"%Y-%m-%d %H:%M:%S" --color=auto'
alias lc='ls -ltr'        #  Sort by/show change time,most recent last.
alias lf=lc
# aliases for the lazy person I am
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias mc='mc -x'
alias ports='sudo netstat -tulanp | less'
alias reboot='sudo /sbin/reboot'
alias shutdown='sudo /sbin/poweroff'
alias ipt='sudo iptables -L -n -v --line-numbers'
alias nat='echo -n "ext IP: ";curl -s https://api.ipify.org;echo'
alias weather='curl http://wttr.in'
alias wipe='shred -n5 -u --zero --verbose --remove=wipesync'
alias wl='while true;cls;date +%Y%b%d\ %T;do ls -hlrtu;sleep 300;done;'
alias tmux.main='tmux new-session -s main \; split-window -h -p 50 \;'
